version: '3'

services:
  client:
    container_name: camformant-client-demo
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    # restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  # server:
  #   container_name: camformant-api-demo
  #   image: jbeanny/camformant-api-demo:latest
  #   restart: always
  #   ports:
  #     - 4000:80
  #   networks:
  #     - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
