import * as React from 'react'

import './../styles/global.css'
import {
  Button,
  Typography,
  Dropdown,
  CategorySelector,
  Icon,
  InputField,
  Shape,
  LinkComponent,
  CheckBox,
  MajorsComponent,
  MajorImage,
  Search,
  Spinner,
} from './atoms'

import {
  Navbar,
  SignUp,
  Filter,
  DetailCard,
  JobContentCard,
  HomeScholarshipCard,
  CardCategory,
  HomeInfoCards,
  ScholarshipContentCard,
  Footer,
  MyModal,
  InfoCard,
  CardCate,
  UploadMenu,
  MobileActionButton,
  InfoSkeleton,
  JobSkeleton,
  ScholarshipSkeleton,
  ScholarshipContentCard2,
  ShareModal,
} from './organisms'

import {
  HomePage,
  JobHeroSection,
  JobBodySection,
  HeroSection,
  BodySection,
  DetailPageHeroSection,
  DetailPageBodySection,
  FormDetail,
  UploadImage,
  Requirement,
  Benefit,
  Contact,
  Description,
  Login,
  SignUpPage,
  ForgotPassword,
  NotFound,
  InfoBody,
  InfoHero,
  InfoDetailPage,
  Profile,
  EditProfile,
  ProHero,
  JobDetail,
  ProfileV2,
  DetailPageBodySection1,
  EditPage,
} from './pages'

export {
  MajorImage,
  MajorsComponent,
  Button,
  Typography,
  Dropdown,
  CategorySelector,
  Icon,
  InputField,
  Shape,
  Search,
  LinkComponent,
  CheckBox,
  Navbar,
  SignUp,
  Filter,
  DetailCard,
  JobContentCard,
  HomeScholarshipCard,
  CardCategory,
  HomeInfoCards,
  ScholarshipContentCard,
  Footer,
  HomePage,
  JobHeroSection,
  JobBodySection,
  HeroSection,
  BodySection,
  InfoCard,
  CardCate,
  DetailPageHeroSection,
  DetailPageBodySection,
  FormDetail,
  UploadImage,
  Requirement,
  Benefit,
  Contact,
  Description,
  UploadMenu,
  Login,
  SignUpPage,
  ForgotPassword,
  NotFound,
  InfoBody,
  InfoHero,
  InfoDetailPage,
  MyModal,
  Profile,
  EditProfile,
  MobileActionButton,
  JobDetail,
  JobSkeleton,
  InfoSkeleton,
  ProfileV2,
  DetailPageBodySection1,
  ScholarshipSkeleton,
  ScholarshipContentCard2,
  EditPage,
  Spinner,
  ShareModal,
}
